{
 "title": "Beehive",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "title": "Gewicht",
   "type": "stat",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Gew. Grüne Beute",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "beehive_green",
     "select": [
      [
       { "params": [ "weight" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Gew. Rote Beute",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "beehive_red",
     "select": [
      [
       { "params": [ "weight" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Delta Gew.",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "grüne Beute",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "beehive_green",
     "query": "SELECT last(\"weight\") - first(\"weight\") FROM \"beehive_green\" WHERE  time > now() - 1d\n",
     "select": [
      [
       { "params": [ "weight" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ],
      [
       { "params": [ "weight" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": " rote Beute",
     "query": "SELECT last(\"weight\") - first(\"weight\") FROM \"beehive_red\" WHERE time > now() - 1d"
    }
   ]
  },
  {
   "title": "Delta Gew. 7d",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Gew. Delta grüne Beute",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "beehive_green",
     "query": "SELECT last(\"weight\") - first(\"weight\") FROM \"beehive_green\" WHERE  time > now() - 7d\n",
     "select": [
      [
       { "params": [ "weight" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ],
      [
       { "params": [ "weight" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "Gew. Delta rote Beute",
     "query": "SELECT last(\"weight\") - first(\"weight\") FROM \"beehive_red\" WHERE time > now() - 7d"
    }
   ]
  },
  {
   "title": "Luftdruck",
   "type": "stat",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pressurembar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Luftdruck",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "beehive_green",
     "select": [
      [
       { "params": [ "pressureGw" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Luftfeuchtigkeit",
   "type": "stat",
   "gridPos": { "h": 12, "w": 5, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Luftfeucht. Innen",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "beehive_green",
     "select": [
      [
       { "params": [ "humidityIn" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Luftfeuchtigkeit Außen",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "beehive_red",
     "select": [
      [
       { "params": [ "humidityOut" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperatur",
   "type": "stat",
   "gridPos": { "h": 12, "w": 5, "x": 19, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Grüne Beute Innentemp.",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "beehive_green",
     "select": [
      [
       { "params": [ "tempIn" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Außentemp.",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "beehive_red",
     "select": [
      [
       { "params": [ "tempOut" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Frequenz in der Beute",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "alias": "Frequenz",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "beehive_green",
     "query": "SELECT mean(\"frequency\") FROM \"beehive_green\" WHERE time >= (now() - 3d)  GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "frequency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}